# Imports

In [1]:
import os
import sys
sys.path.append(os.path.abspath("../"))
from src import cleaning

import pandas as pd
import numpy as np

import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


%load_ext autoreload
%autoreload 2

# Extract

In [2]:
data = "../data/unclean.csv"

In [3]:
df = pd.read_csv(data, sep=",", encoding="utf-8")

It is obvious from the output below that both:
1. initial cleaning (mostly normalization) and
2. formatting (number formatting) are needed.

In [4]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order@ID          194 non-null    object
 1   Customer@Name     194 non-null    object
 2   Contact@Info      155 non-null    object
 3   Product@Category  200 non-null    object
 4   Sale@Price        194 non-null    float64
 5   Order@Date        200 non-null    object
 6   Delivery@Date     200 non-null    object
 7   Inventory@Count   194 non-null    float64
 8   Discount@Rate     200 non-null    float64
 9   Regional@Code     200 non-null    object
dtypes: float64(3), object(7)
memory usage: 15.8+ KB

,Order@ID,Customer@Name,Contact@Info,Product@Category,Sale@Price,Order@Date,Delivery@Date,Inventory@Count,Discount@Rate,Regional@Code
0,ORD_1,dR. aLICE bROWN,Email: alice@mail.com,electronics,1200.50,2023-01-01,2023-01-05,50.0,0.10,USA-NY-10001
1,ORD_2,mrs. bob smith,Phone: 555-0101,HOME DECOR,45.99,2023-01-01,2023-01-05,150.0,0.15,CAN-ON-M5V
2,ORD_3,mr. charlie davis,NaN,Clothing,89.00,2023-01-01,2023-01-05,200.0,0.05,USA-CA-90210
3,ORD_4,Mrs. David Wilson,Phone: 555-0103,Electronics,150.00,2023-01-01,2023-01-05,30.0,0.85,GER-BER-10115
4,ORD_5,NaN,Email: eve@mail.com,hOME dECOR,12.50,2023-01-01,2023-01-05,500.0,0.12,UK-LON-EC1A

# Clean
## Initialize

Column names will be freed of unwanted char '@':

In [5]:
df.columns = [column.replace("@", "_") for column in df.columns.tolist()]

An object from Cleaning class will be generated below to handle some of the cleaning operations while carrying the self-object 'df'.

In [6]:
cleaner = cleaning.Cleaning(df=df)

## Initial cleaning

Columns' content will be freed from unwanted chars below via Cleaner method 'str_clean':

In [7]:
cleaner.str_clean(columns_chars= {"Contact_Info": r".*?[:_]", "Order_ID":r".*?[:_]", "Customer_Name": r".*?\."}, regex=True).head()

27 - 01-05-2026 03.45:15 - INFO - str_clean - Function is called.
33 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process STARTED for column Contact_Info and for char .*?[:_].
35 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process COMPLETED SUCCESSFULLY for column Contact_Info and for char .*?[:_].

The column 'Contact_Info':cleaned.

33 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process STARTED for column Order_ID and for char .*?[:_].
35 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process COMPLETED SUCCESSFULLY for column Order_ID and for char .*?[:_].

The column 'Order_ID':cleaned.

33 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process STARTED for column Customer_Name and for char .*?\..
35 - 01-05-2026 03.45:15 - DEBUG - str_clean - Process COMPLETED SUCCESSFULLY for column Customer_Name and for char .*?\..

The column 'Customer_Name':cleaned.

     Contact_Info Order_ID  Customer_Name
0  alice@mail.com        1    aLICE bROWN
1        555-0101        2      bob smith
2             NaN        3  charlie davis
3        555-0103        4   David Wilson
4    eve@mail.com        5            NaN

Columns' content will be assigned cases as desired below via Cleaner method 'assign_cases':

In [8]:
cleaner.case_assign(columns_cases={"Product_Category": "title", "Customer_Name": "title"}).head()

52 - 01-05-2026 03.45:15 - INFO - case_assign - Function is called.
58 - 01-05-2026 03.45:15 - DEBUG - case_assign - Process STARTED for column Product_Category and for case title.
61 - 01-05-2026 03.45:15 - DEBUG - case_assign - Process COMPLETED SUCCESSFULLY for column Product_Category and for case title.

The column 'Product_Category':title case assigned.

58 - 01-05-2026 03.45:15 - DEBUG - case_assign - Process STARTED for column Customer_Name and for case title.
61 - 01-05-2026 03.45:15 - DEBUG - case_assign - Process COMPLETED SUCCESSFULLY for column Customer_Name and for case title.

The column 'Customer_Name':title case assigned.

  Product_Category  Customer_Name
0      Electronics    Alice Brown
1       Home Decor      Bob Smith
2         Clothing  Charlie Davis
3      Electronics   David Wilson
4       Home Decor            NaN

## Formatting

Columns' content will be formatted as desired below:

In [9]:
cleaner.df = cleaner.df.astype({
	"Order_ID" : "string",
	"Customer_Name" : "string",
	"Contact_Info" : "string",
	"Product_Category" : "string",
	"Regional_Code" : "string",
	"Sale_Price": "float64",
	"Inventory_Count": "float64"
})
cleaner.df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          194 non-null    string
 1   Customer_Name     194 non-null    string
 2   Contact_Info      155 non-null    string
 3   Product_Category  200 non-null    string
 4   Sale_Price        194 non-null    float64
 5   Order_Date        200 non-null    object
 6   Delivery_Date     200 non-null    object
 7   Inventory_Count   194 non-null    float64
 8   Discount_Rate     200 non-null    float64
 9   Regional_Code     200 non-null    string
dtypes: float64(3), object(2), string(5)
memory usage: 15.8+ KB

In [10]:
cleaner.df["Sale_Price"] = cleaner.df["Sale_Price"].round(2)
cleaner.df["Inventory_Count"] = cleaner.df["Inventory_Count"].round().astype("Int64")

Date columns' data type will be changed as desired below, via Cleaner method 'datetime_converter', to be able to conduct calculations if needed down the run:

In [11]:
cleaner.datetime_converter(columns=["Order_Date", "Delivery_Date"], to="datetime").info()

79 - 01-05-2026 03.45:16 - INFO - datetime_converter - Function is called.
86 - 01-05-2026 03.45:16 - DEBUG - datetime_converter - Process STARTED for column Order_Date and for the format datetime.
88 - 01-05-2026 03.45:16 - DEBUG - datetime_converter - Process ENDED SUCCESSFULLY for column Order_Date and for the format datetime.

86 - 01-05-2026 03.45:16 - DEBUG - datetime_converter - Process STARTED for column Delivery_Date and for the format datetime.
88 - 01-05-2026 03.45:16 - DEBUG - datetime_converter - Process ENDED SUCCESSFULLY for column Delivery_Date and for the format datetime.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Date     200 non-null    datetime64[ns]
 1   Delivery_Date  200 non-null    datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 3.2 KB

## Missing values

Missing values in the columns will be observed below via constructing desired boolean relations between columns through Cleaner method 'null_rows' to decide in the next step how to treat them:

In [12]:
columns= ["Customer_Name", "Contact_Info"]
cleaner.null_rows(columns=columns, separator="&")

columns= ["Order_ID", "Sale_Price", "Order_Date", "Delivery_Date"]
cleaner.null_rows(columns=columns, separator="|")

119 - 01-05-2026 03.45:17 - INFO - null_rows - Function is called.
122 - 01-05-2026 03.45:17 - DEBUG - null_rows - Process STARTED for the separator &.
130 - 01-05-2026 03.45:17 - DEBUG - null_rows - Process ENDED SUCCESSFULLY for the separator &.

'Null row count: 0'

119 - 01-05-2026 03.45:17 - INFO - null_rows - Function is called.
122 - 01-05-2026 03.45:17 - DEBUG - null_rows - Process STARTED for the separator |.
130 - 01-05-2026 03.45:17 - DEBUG - null_rows - Process ENDED SUCCESSFULLY for the separator |.

'Null row count: 12'

The rows observed above with null values will be dropped below:

In [13]:
cleaner.df = cleaner.df.dropna(how="all", subset=["Customer_Name", "Contact_Info"], axis=0).reset_index(drop=True)
cleaner.df = cleaner.df.dropna(how="any", subset=["Order_ID", "Sale_Price", "Order_Date", "Delivery_Date"], axis=0).reset_index(drop=True)

## Duplicates

Total row count that contains duplicated values in the "Order_ID" column will be observed as no duplication in this column is envisaged:

In [14]:
cleaner.df["Order_ID"].duplicated().sum()

np.int64(0)

In [15]:
cleaner.df.duplicated().sum()

np.int64(0)

## Outliers

Below, discount_Rate column values are capped at the value 0.75 as no further discount rate is assumed:

In [16]:
cleaner.df.loc[:, "Discount_Rate"] = cleaner.df["Discount_Rate"].clip(upper=0.75)
cleaner.df[["Discount_Rate"]].sort_values(by="Discount_Rate", ascending=False).head()

    Discount_Rate
3            0.75
7            0.75
11           0.75
15           0.75
20           0.75

Below z_score method will be employed to track the outliers in the Sale_Price column via Cleaner method 'outlier_z'. It will show the range bins of z_score values:

In [17]:
cleaner.outlier_z(op="bins", col="Sale_Price", group_by="Product_Category", z_abs_thresh=1)

145 - 01-05-2026 03.45:18 - INFO - outlier_z - Function is called.
167 - 01-05-2026 03.45:18 - DEBUG - _bins - Process STARTED for column Sale_Price and for the param 'bins'.
'Sale_Price' has 116 cells in the z score range of 1.
 'Sale_Price' has 72 cells out of the z score range of 1.

   z_scores_Sale_Price
0             1.033871
1             1.020437
2             0.000000
3            -0.954342
4            -0.966730

Values inside the range 1 (head):

   z_scores_Sale_Price
2             0.000000
3            -0.954342
4            -0.966730
6             0.000000
7            -0.954342

Values outside the range 1 (head):

    z_scores_Sale_Price
0              1.033871
1              1.020437
5              1.033871
9              1.020437
13             1.020437

180 - 01-05-2026 03.45:18 - DEBUG - _bins - Process COMPLETED SUCCESSFULLY for column Sale_Price and for the param 'bins'.

Below iqr method will be employed to track the outliers in the Sale_Price column, through Cleaner method 'outlier_iqr'. It will show the range bins of outliers:

In [18]:
cleaner.outlier_iqr(op="bins", col="Sale_Price", coef=0.5)

202 - 01-05-2026 03.45:18 - INFO - outlier_iqr - Function is called.
216 - 01-05-2026 03.45:18 - DEBUG - _bins - Process STARTED for column Sale_Price and for the operation 'bins'.
'Sale_Price' has 0 cells that falls under quantile [0.25, 0.75].
 'Sale_Price' has 36 cells that go beyond quantile [0.25, 0.75].

Values inside the quantiles [0.25, 0.75] (head):

   Sale_Price
1       45.99
2       89.00
3      150.00
4       12.50
6       89.00

Values outside the quantiles [0.25, 0.75] (head):

    Sale_Price
0       1200.5
5       1200.5
17      1200.5
22      1200.5
27      1200.5

225 - 01-05-2026 03.45:18 - DEBUG - _bins - Process COMPLETED SUCCESSFULLY for column Sale_Price and for the param 'bins'.

Below df_z will be created out of the z_score values in the df:

In [19]:
df_z = cleaner.outlier_z(op="adopt", col="Sale_Price", group_by="Product_Category", z_abs_thresh=1)
df_z

145 - 01-05-2026 03.45:19 - INFO - outlier_z - Function is called.
183 - 01-05-2026 03.45:19 - DEBUG - _adopt - Process STARTED for column Sale_Price and for the param 'adopt'.

,Order_ID,Customer_Name,Contact_Info,Product_Category,Sale_Price,Order_Date,Delivery_Date,Inventory_Count,Discount_Rate,Regional_Code,z_scores_Sale_Price
0,3,Charlie Davis,<NA>,Clothing,89.0,2023-01-01,2023-01-05,200,0.05,USA-CA-90210,0.000000
1,4,David Wilson,555-0103,Electronics,150.0,2023-01-01,2023-01-05,30,0.75,GER-BER-10115,-0.954342
2,5,<NA>,eve@mail.com,Home Decor,12.5,2023-01-01,2023-01-05,500,0.12,UK-LON-EC1A,-0.966730
3,8,Hank Anderson,<NA>,Clothing,89.0,2023-01-01,2023-01-05,200,0.05,USA-CA-90210,0.000000
4,9,Ivy Thomas,ivy@mail.com,Electronics,150.0,2023-01-01,2023-01-05,30,0.75,GER-BER-10115,-0.954342
...,...,...,...,...,...,...,...,...,...,...,...
111,193,Charlie Davis,charlie@mail.com,Clothing,89.0,2023-01-01,2023-01-05,200,0.05,USA-CA-90210,0.000000
112,194,David Wilson,555-0103,Electronics,150.0,2023-01-01,2023-01-05,<NA>,0.75,GER-BER-10115,-0.954342
113,195,Eve Miller,eve@mail.com,Home Decor,12.5,2023-01-01,2023-01-05,500,0.12,UK-LON-EC1A,-0.966730
114,198,Hank Anderson,555-0107,Clothing,89.0,2023-01-01,2023-01-05,<NA>,0.05,USA-CA-90210,0.000000
115,199,Ivy Thomas,ivy@mail.com,Electronics,150.0,2023-01-01,2023-01-05,30,0.75,GER-BER-10115,-0.954342

Below df_iqr will be created out of the iqr outliers in the df:

In [20]:
df_iqr = cleaner.outlier_iqr(op="adopt", col="Sale_Price", coef=0.5)
df_iqr

202 - 01-05-2026 03.45:19 - INFO - outlier_iqr - Function is called.
228 - 01-05-2026 03.45:19 - DEBUG - _adopt - Process STARTED for column Sale_Price and for the operation 'adopt'.

,Order_ID,Customer_Name,Contact_Info,Product_Category,Sale_Price,Order_Date,Delivery_Date,Inventory_Count,Discount_Rate,Regional_Code,z_scores_Sale_Price
0,2,Bob Smith,555-0101,Home Decor,45.99,2023-01-01,2023-01-05,150,0.15,CAN-ON-M5V,1.020437
1,3,Charlie Davis,<NA>,Clothing,89.00,2023-01-01,2023-01-05,200,0.05,USA-CA-90210,0.000000
2,4,David Wilson,555-0103,Electronics,150.00,2023-01-01,2023-01-05,30,0.75,GER-BER-10115,-0.954342
3,5,<NA>,eve@mail.com,Home Decor,12.50,2023-01-01,2023-01-05,500,0.12,UK-LON-EC1A,-0.966730
4,8,Hank Anderson,<NA>,Clothing,89.00,2023-01-01,2023-01-05,200,0.05,USA-CA-90210,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
147,194,David Wilson,555-0103,Electronics,150.00,2023-01-01,2023-01-05,<NA>,0.75,GER-BER-10115,-0.954342
148,195,Eve Miller,eve@mail.com,Home Decor,12.50,2023-01-01,2023-01-05,500,0.12,UK-LON-EC1A,-0.966730
149,197,Grace Taylor,grace@mail.com,Home Decor,45.99,2023-01-01,2023-01-05,150,0.15,CAN-ON-M5V,1.020437
150,198,Hank Anderson,555-0107,Clothing,89.00,2023-01-01,2023-01-05,<NA>,0.05,USA-CA-90210,0.000000
151,199,Ivy Thomas,ivy@mail.com,Electronics,150.00,2023-01-01,2023-01-05,30,0.75,GER-BER-10115,-0.954342

Below df_z will be selected and assigned to the df that the cleaner object carries:

In [21]:
cleaner.df = df_iqr

# Transform
## Manipulation

Below, columns will be reordered as desired, through Cleaner method 'column_reorder':

In [22]:
cleaner.column_reorder(columns_idx={"Customer_Name": 1, "Inventory_Count": 4, "Discount_Rate": 6, 'z_scores_Sale_Price': 7}).columns.tolist()

246 - 01-05-2026 03.45:20 - INFO - column_reorder - Function is called.
247 - 01-05-2026 03.45:20 - DEBUG - column_reorder - Process STARTED.
257 - 01-05-2026 03.45:20 - DEBUG - column_reorder - Process COMPLETED SUCCESSFULLY.

['Order_ID',
 'Customer_Name',
 'Contact_Info',
 'Product_Category',
 'Inventory_Count',
 'Sale_Price',
 'Discount_Rate',
 'z_scores_Sale_Price',
 'Order_Date',
 'Delivery_Date',
 'Regional_Code']

## Enrich

Below, two columns -'Email' and 'Tel_Nu'- will be generated and populated with the content of 'Cantact_Info' column as this column both incoporates email and telephone number values at the same time:

In [23]:
cleaner.df.loc[:, "Email"] = df["Contact_Info"].where(df["Contact_Info"].str.contains("com|org", na=False)).astype("string")
cleaner.df.loc[:, "Tel_Nu"] = df["Contact_Info"].where(~df["Contact_Info"].str.contains("com|org", na=False)).astype("string")
cleaner.df[["Email", "Tel_Nu"]].head()
cleaner.df = cleaner.df.drop(columns=("Contact_Info"))

            Email    Tel_Nu
0  alice@mail.com      <NA>
1            <NA>  555-0101
2            <NA>      <NA>
3            <NA>  555-0103
4    eve@mail.com      <NA>

Below, columns will be reordered as desired, through Cleaner method 'column_reorder':

In [24]:
cleaner.column_reorder({"Email": 2, "Tel_Nu": 2}).columns.tolist()

246 - 01-05-2026 03.45:20 - INFO - column_reorder - Function is called.
247 - 01-05-2026 03.45:20 - DEBUG - column_reorder - Process STARTED.
257 - 01-05-2026 03.45:20 - DEBUG - column_reorder - Process COMPLETED SUCCESSFULLY.

['Order_ID',
 'Customer_Name',
 'Tel_Nu',
 'Email',
 'Product_Category',
 'Inventory_Count',
 'Sale_Price',
 'Discount_Rate',
 'z_scores_Sale_Price',
 'Order_Date',
 'Delivery_Date',
 'Regional_Code']

Below, new row entries will be generated through Cleaner method 'numeric_entry_df_generator' -with only numeric columns populated- for only to be incoporated into the df  / cleaner object later on:

In [25]:
df_new_entry = cleaner.numeric_entry_df_generator(entry_num=3)
df_new_entry

267 - 01-05-2026 03.45:20 - INFO - numeric_entry_df_generator - Function is called.
270 - 01-05-2026 03.45:20 - DEBUG - numeric_entry_df_generator - Process STARTED.
294 - 01-05-2026 03.45:20 - DEBUG - numeric_entry_df_generator - Process COMPLETED SUCCESSFULLY.

,Order_ID,Customer_Name,Tel_Nu,Email,Product_Category,Inventory_Count,Sale_Price,Discount_Rate,z_scores_Sale_Price,Order_Date,Delivery_Date,Regional_Code
0,NaN,NaN,NaN,NaN,NaN,357,111.23,0.08,0.60,NaT,NaT,NaN
1,NaN,NaN,NaN,NaN,NaN,87,36.73,0.56,0.03,NaT,NaT,NaN
2,NaN,NaN,NaN,NaN,NaN,42,20.93,0.41,0.10,NaT,NaT,NaN

Below: new row entries will be concatenated into the df:

In [26]:
cleaner.df = pd.concat([cleaner.df, df_new_entry], ignore_index=True, axis=0)
cleaner.df

,Order_ID,Customer_Name,Tel_Nu,Email,Product_Category,Inventory_Count,Sale_Price,Discount_Rate,z_scores_Sale_Price,Order_Date,Delivery_Date,Regional_Code
0,2,Bob Smith,<NA>,alice@mail.com,Home Decor,150,45.99,0.15,1.020437,2023-01-01,2023-01-05,CAN-ON-M5V
1,3,Charlie Davis,555-0101,<NA>,Clothing,200,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
2,4,David Wilson,<NA>,<NA>,Electronics,30,150.00,0.75,-0.954342,2023-01-01,2023-01-05,GER-BER-10115
3,5,<NA>,555-0103,<NA>,Home Decor,500,12.50,0.12,-0.966730,2023-01-01,2023-01-05,UK-LON-EC1A
4,8,Hank Anderson,<NA>,eve@mail.com,Clothing,200,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
...,...,...,...,...,...,...,...,...,...,...,...,...
150,198,Hank Anderson,<NA>,alice@mail.com,Clothing,<NA>,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
151,199,Ivy Thomas,555-0101,<NA>,Electronics,30,150.00,0.75,-0.954342,2023-01-01,2023-01-05,GER-BER-10115
152,<NA>,<NA>,<NA>,<NA>,<NA>,357,111.23,0.08,0.600000,NaT,NaT,<NA>
153,<NA>,<NA>,<NA>,<NA>,<NA>,87,36.73,0.56,0.030000,NaT,NaT,<NA>
154,<NA>,<NA>,<NA>,<NA>,<NA>,42,20.93,0.41,0.100000,NaT,NaT,<NA>

# Validate

Below, it will be validated that the all regional codes in the 'Regional_Code' column starts with the defined region abbreviations:

In [27]:
regions = ["USA", "CAN", "GER", "UK"]
mask_regions = cleaner.df["Regional_Code"].str.split("-").str[0].isin(regions)
mask_na = cleaner.df["Regional_Code"].isna()
mask_regions.sum() + mask_na.sum() == cleaner.df.shape[0]

np.True_

Below, it will be validated that no date value in the Order_Date column is more recent than the corresponding date value in the 'Delivery_Date' column:

In [28]:
any(cleaner.df['Order_Date'] > cleaner.df['Delivery_Date'])

False

# Operations and Aggregation

Below, product categories will be observed to be able to conduct groupings over the 'Product_Category' column later on:

In [29]:
set(df["Product_Category"])

{'Clothing', 'Electronics', 'Home Decor'}

Below: two new columns -'Avg_Sale_Price_By_Product_Category' and 'Total_Inventory_Count_By_Product_Category'- will be generated via aggregations over 'Sale_Price' and 'Inventory_Count' columns respectively by grouping product categories, to see relevant performance data by product group:

In [30]:
cleaner.df["Avg_Sale_Price_By_Product_Category"] = cleaner.df.groupby("Product_Category")["Sale_Price"].transform(lambda cell: cell.mean().round(2))

cleaner.df["Total_Inventory_Count_By_Product_Category"] = cleaner.df.groupby("Product_Category")["Inventory_Count"].transform(func="sum")

cleaner.df[["Product_Category", "Avg_Sale_Price_By_Product_Category", "Total_Inventory_Count_By_Product_Category"]].head()

,Product_Category,Avg_Sale_Price_By_Product_Category,Total_Inventory_Count_By_Product_Category
0,Home Decor,28.79,24250
1,Clothing,89.00,7400
2,Electronics,150.00,1140
3,Home Decor,28.79,24250
4,Clothing,89.00,7400

Below, columns will be reordered as desired via Cleaner method 'column_reorder':

In [31]:
cleaner.column_reorder(columns_idx={'Total_Inventory_Count_By_Product_Category': 6, 'Avg_Sale_Price_By_Product_Category': 8})

246 - 01-05-2026 03.45:22 - INFO - column_reorder - Function is called.
247 - 01-05-2026 03.45:22 - DEBUG - column_reorder - Process STARTED.
257 - 01-05-2026 03.45:22 - DEBUG - column_reorder - Process COMPLETED SUCCESSFULLY.

,Order_ID,Customer_Name,Tel_Nu,Email,Product_Category,Inventory_Count,Total_Inventory_Count_By_Product_Category,Sale_Price,Avg_Sale_Price_By_Product_Category,Discount_Rate,z_scores_Sale_Price,Order_Date,Delivery_Date,Regional_Code
0,2,Bob Smith,<NA>,alice@mail.com,Home Decor,150,24250,45.99,28.79,0.15,1.020437,2023-01-01,2023-01-05,CAN-ON-M5V
1,3,Charlie Davis,555-0101,<NA>,Clothing,200,7400,89.00,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
2,4,David Wilson,<NA>,<NA>,Electronics,30,1140,150.00,150.00,0.75,-0.954342,2023-01-01,2023-01-05,GER-BER-10115
3,5,<NA>,555-0103,<NA>,Home Decor,500,24250,12.50,28.79,0.12,-0.966730,2023-01-01,2023-01-05,UK-LON-EC1A
4,8,Hank Anderson,<NA>,eve@mail.com,Clothing,200,7400,89.00,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,198,Hank Anderson,<NA>,alice@mail.com,Clothing,<NA>,7400,89.00,89.00,0.05,0.000000,2023-01-01,2023-01-05,USA-CA-90210
151,199,Ivy Thomas,555-0101,<NA>,Electronics,30,1140,150.00,150.00,0.75,-0.954342,2023-01-01,2023-01-05,GER-BER-10115
152,<NA>,<NA>,<NA>,<NA>,<NA>,357,<NA>,111.23,NaN,0.08,0.600000,NaT,NaT,<NA>
153,<NA>,<NA>,<NA>,<NA>,<NA>,87,<NA>,36.73,NaN,0.56,0.030000,NaT,NaT,<NA>
154,<NA>,<NA>,<NA>,<NA>,<NA>,42,<NA>,20.93,NaN,0.41,0.100000,NaT,NaT,<NA>

Below: 'Regional_Code' is grouped and 'Inventory_Count' and 'Order_ID' columns will be aggregated via mean and count functions respectively to see the products of which reginal code have what inventory count and brought about how many orders:

In [32]:
df_regional_code = cleaner.df.groupby("Regional_Code").agg({"Inventory_Count": "mean", "Order_ID": "count"})
df_regional_code

               Inventory_Count  Order_ID
Regional_Code
CAN-ON-M5V               150.0        36
GER-BER-10115             30.0        39
UK-LON-EC1A              500.0        38
USA-CA-90210             200.0        39

Below, the df will be resampled on 'Order_Date' date column to have a holistic / monthly insight on the numeric columns:

In [33]:
cleaner.df.info()
df_resampled = cleaner.df.resample(on="Order_Date", rule="W", closed="left", label="left").mean(numeric_only=True).drop(columns="z_scores_Sale_Price")
df_resampled

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 14 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Order_ID                                   152 non-null    string
 1   Customer_Name                              148 non-null    string
 2   Tel_Nu                                     61 non-null     string
 3   Email                                      57 non-null     string
 4   Product_Category                           152 non-null    string
 5   Inventory_Count                            151 non-null    Int64
 6   Total_Inventory_Count_By_Product_Category  152 non-null    Int64
 7   Sale_Price                                 155 non-null    float64
 8   Avg_Sale_Price_By_Product_Category         152 non-null    float64
 9   Discount_Rate                              155 non-null    float64
 10  z_scores_Sale_Price                        155 non-null    float64
 11  Order_Date                                 152 non-null    datetime64[ns]
 12  Delivery_Date                              152 non-null    datetime64[ns]
 13  Regional_Code                              152 non-null    string
dtypes: Int64(2), datetime64[ns](2), float64(4), string(6)
memory usage: 17.4 KB

,Inventory_Count,Total_Inventory_Count_By_Product_Category,Sale_Price,Avg_Sale_Price_By_Product_Category,Discount_Rate
Order_Date,,,,,
2023-01-01,221.554054,13997.105263,75.339737,75.338553,0.270789

# Output

Date columns' data type will be changed into string dtype below, via Cleaner method 'datetime_converter':

In [34]:
cleaner.datetime_converter(columns=["Order_Date", "Delivery_Date"], to="str").info()

79 - 01-05-2026 03.45:23 - INFO - datetime_converter - Function is called.
99 - 01-05-2026 03.45:23 - DEBUG - datetime_converter - Process ENDED SUCCESSFULLY for column Order_Date and for the format str.

99 - 01-05-2026 03.45:23 - DEBUG - datetime_converter - Process ENDED SUCCESSFULLY for column Delivery_Date and for the format str.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Date     152 non-null    string
 1   Delivery_Date  152 non-null    string
dtypes: string(2)
memory usage: 2.5 KB

In [35]:
cleaner.df["Order_ID"] = cleaner.df["Order_ID"].astype("Int64")
cleaner.df = cleaner.df.set_index("Order_ID").sort_index()
cleaner.df.info()
cleaner.df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 2 to <NA>
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Customer_Name                              148 non-null    string
 1   Tel_Nu                                     61 non-null     string
 2   Email                                      57 non-null     string
 3   Product_Category                           152 non-null    string
 4   Inventory_Count                            151 non-null    Int64
 5   Total_Inventory_Count_By_Product_Category  152 non-null    Int64
 6   Sale_Price                                 155 non-null    float64
 7   Avg_Sale_Price_By_Product_Category         152 non-null    float64
 8   Discount_Rate                              155 non-null    float64
 9   z_scores_Sale_Price                        155 non-null    float64
 10  Order_Date                                 152 non-null    string
 11  Delivery_Date                              152 non-null    string
 12  Regional_Code                              152 non-null    string
dtypes: Int64(2), float64(4), string(7)
memory usage: 17.4 KB

,Customer_Name,Tel_Nu,Email,Product_Category,Inventory_Count,Total_Inventory_Count_By_Product_Category,Sale_Price,Avg_Sale_Price_By_Product_Category,Discount_Rate,z_scores_Sale_Price,Order_Date,Delivery_Date,Regional_Code
Order_ID,,,,,,,,,,,,,
2,Bob Smith,<NA>,alice@mail.com,Home Decor,150,24250,45.99,28.79,0.15,1.020437,01.01.2023,05.01.2023,CAN-ON-M5V
3,Charlie Davis,555-0101,<NA>,Clothing,200,7400,89.00,89.00,0.05,0.000000,01.01.2023,05.01.2023,USA-CA-90210
4,David Wilson,<NA>,<NA>,Electronics,30,1140,150.00,150.00,0.75,-0.954342,01.01.2023,05.01.2023,GER-BER-10115
5,<NA>,555-0103,<NA>,Home Decor,500,24250,12.50,28.79,0.12,-0.966730,01.01.2023,05.01.2023,UK-LON-EC1A
8,Hank Anderson,<NA>,eve@mail.com,Clothing,200,7400,89.00,89.00,0.05,0.000000,01.01.2023,05.01.2023,USA-CA-90210

In [36]:
cleaner.df.to_csv("../data/clean.csv", sep=",", index=True, encoding="utf-8")